import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Providers from "@/utils/provider";
import {ReactNode} from "react";
import {LayoutApp} from "@/components/layout/layoutApp";

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Shop online',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <LayoutApp>
          <Providers>{children}</Providers>
      </LayoutApp>
      </body>
    </html>
  )
}
